#!/usr/bin/env python
#-*-coding:utf-8-*- 
import numpy as np  
import pandas as pd
import plotly.plotly as py
import plotly.graph_objs as go
from sklearn import preprocessing

uselessid = ["UNITID","OPEID","opeid6","INSTNM","CITY","STABBR","ZIP","AccredAgency"]#,"INSTURL","NPCURL","sch_deg","st_fips","RELAFFIL"]
filenames = ["MERGED1996_PP.csv","MERGED1997_PP.csv","MERGED1998_PP.csv","MERGED1999_PP.csv","MERGED2000_PP.csv","MERGED2001_PP.csv","MERGED2002_PP.csv","MERGED2003_PP.csv","MERGED2004_PP.csv","MERGED2005_PP.csv","MERGED2006_PP.csv","MERGED2007_PP.csv","MERGED2008_PP.csv","MERGED2009_PP.csv","MERGED2010_PP.csv","MERGED2011_PP.csv","MERGED2012_PP.csv","MERGED2013_PP.csv"]

allid = ["ADM_RATE","ADM_RATE_ALL","SATVRMID","SATMTMID","SATWRMID","ACTCMMID","ACTENMID","ACTMTMID","ACTWRMID","SAT_AVG","SAT_AVG_ALL","UGDS","UG","PPTUG_EF","PPTUG_EF2","NPT4_PUB","NPT4_PRIV","NPT4_PROG","NPT4_OTHER","NPT41_PUB","NPT42_PUB","NPT43_PUB","NPT44_PUB","NPT45_PUB","NPT41_PRIV","NPT42_PRIV","NPT43_PRIV","NPT44_PRIV","NPT45_PRIV","NPT41_PROG","NPT42_PROG","NPT43_PROG","NPT44_PROG","NPT45_PROG","NPT41_OTHER","NPT42_OTHER","NPT43_OTHER","NPT44_OTHER","NPT45_OTHER","NPT4_048_PUB","NPT4_048_PRIV","NPT4_048_PROG","NPT4_048_OTHER","NPT4_3075_PUB","NPT4_3075_PRIV","NPT4_75UP_PUB","NPT4_75UP_PRIV","NPT4_3075_PROG","NPT4_3075_OTHER","NPT4_75UP_PROG","NPT4_75UP_OTHER","NUM4_PUB","NUM4_PRIV","NUM4_PROG","NUM4_OTHER","NUM41_PUB","NUM42_PUB","NUM43_PUB","NUM44_PUB","NUM45_PUB","NUM41_PRIV","NUM42_PRIV","NUM43_PRIV","NUM44_PRIV","NUM45_PRIV","NUM41_PROG","NUM42_PROG","NUM43_PROG","NUM44_PROG","NUM45_PROG","NUM41_OTHER","NUM42_OTHER","NUM43_OTHER","NUM44_OTHER","NUM45_OTHER","COSTT4_A","COSTT4_P","TUITIONFEE_IN","TUITIONFEE_OUT","TUITIONFEE_PROG","TUITFTE","INEXPFTE","AVGFACSAL","PFTFAC","PCTPELL","C150_4","C150_L4","C150_4_POOLED","C150_L4_POOLED","poolyrs","PFTFTUG1_EF","RET_FT4","RET_FTL4","RET_PT4","RET_PTL4","PCTFLOAN","UG25abv","CDR2","CDR3","DEATH_YR4_RT","COMP_ORIG_YR4_RT","COMP_4YR_TRANS_YR4_RT","COMP_2YR_TRANS_YR4_RT","WDRAW_ORIG_YR4_RT","WDRAW_4YR_TRANS_YR4_RT","WDRAW_2YR_TRANS_YR4_RT","ENRL_ORIG_YR4_RT","ENRL_4YR_TRANS_YR4_RT","ENRL_2YR_TRANS_YR4_RT","UNKN_ORIG_YR4_RT","UNKN_4YR_TRANS_YR4_RT","UNKN_2YR_TRANS_YR4_RT","LO_INC_DEATH_YR4_RT","LO_INC_COMP_ORIG_YR4_RT","LO_INC_COMP_4YR_TRANS_YR4_RT","LO_INC_COMP_2YR_TRANS_YR4_RT","LO_INC_WDRAW_ORIG_YR4_RT","LO_INC_WDRAW_4YR_TRANS_YR4_RT","LO_INC_WDRAW_2YR_TRANS_YR4_RT","LO_INC_ENRL_ORIG_YR4_RT","LO_INC_ENRL_4YR_TRANS_YR4_RT","LO_INC_ENRL_2YR_TRANS_YR4_RT","LO_INC_UNKN_ORIG_YR4_RT","LO_INC_UNKN_4YR_TRANS_YR4_RT","LO_INC_UNKN_2YR_TRANS_YR4_RT","MD_INC_DEATH_YR4_RT","MD_INC_COMP_ORIG_YR4_RT","MD_INC_COMP_4YR_TRANS_YR4_RT","MD_INC_COMP_2YR_TRANS_YR4_RT","MD_INC_WDRAW_ORIG_YR4_RT","MD_INC_WDRAW_4YR_TRANS_YR4_RT","MD_INC_WDRAW_2YR_TRANS_YR4_RT","MD_INC_ENRL_ORIG_YR4_RT","MD_INC_ENRL_4YR_TRANS_YR4_RT","MD_INC_ENRL_2YR_TRANS_YR4_RT","MD_INC_UNKN_ORIG_YR4_RT","MD_INC_UNKN_4YR_TRANS_YR4_RT","MD_INC_UNKN_2YR_TRANS_YR4_RT","HI_INC_DEATH_YR4_RT","HI_INC_COMP_ORIG_YR4_RT","HI_INC_COMP_4YR_TRANS_YR4_RT","HI_INC_COMP_2YR_TRANS_YR4_RT","HI_INC_WDRAW_ORIG_YR4_RT","HI_INC_WDRAW_4YR_TRANS_YR4_RT","HI_INC_WDRAW_2YR_TRANS_YR4_RT","HI_INC_ENRL_ORIG_YR4_RT","HI_INC_ENRL_4YR_TRANS_YR4_RT","HI_INC_ENRL_2YR_TRANS_YR4_RT","HI_INC_UNKN_ORIG_YR4_RT","HI_INC_UNKN_4YR_TRANS_YR4_RT","HI_INC_UNKN_2YR_TRANS_YR4_RT","DEP_DEATH_YR4_RT","DEP_COMP_ORIG_YR4_RT","DEP_COMP_4YR_TRANS_YR4_RT","DEP_COMP_2YR_TRANS_YR4_RT","DEP_WDRAW_ORIG_YR4_RT","DEP_WDRAW_4YR_TRANS_YR4_RT","DEP_WDRAW_2YR_TRANS_YR4_RT","DEP_ENRL_ORIG_YR4_RT","DEP_ENRL_4YR_TRANS_YR4_RT","DEP_ENRL_2YR_TRANS_YR4_RT","DEP_UNKN_ORIG_YR4_RT","DEP_UNKN_4YR_TRANS_YR4_RT","DEP_UNKN_2YR_TRANS_YR4_RT","IND_DEATH_YR4_RT","IND_COMP_ORIG_YR4_RT","IND_COMP_4YR_TRANS_YR4_RT","IND_COMP_2YR_TRANS_YR4_RT","IND_WDRAW_ORIG_YR4_RT","IND_WDRAW_4YR_TRANS_YR4_RT","IND_WDRAW_2YR_TRANS_YR4_RT","IND_ENRL_ORIG_YR4_RT","IND_ENRL_4YR_TRANS_YR4_RT","IND_ENRL_2YR_TRANS_YR4_RT","IND_UNKN_ORIG_YR4_RT","IND_UNKN_4YR_TRANS_YR4_RT","IND_UNKN_2YR_TRANS_YR4_RT","FEMALE_DEATH_YR4_RT","FEMALE_COMP_ORIG_YR4_RT","FEMALE_COMP_4YR_TRANS_YR4_RT","FEMALE_COMP_2YR_TRANS_YR4_RT","FEMALE_WDRAW_ORIG_YR4_RT","FEMALE_WDRAW_4YR_TRANS_YR4_RT","FEMALE_WDRAW_2YR_TRANS_YR4_RT","FEMALE_ENRL_ORIG_YR4_RT","FEMALE_ENRL_4YR_TRANS_YR4_RT","FEMALE_ENRL_2YR_TRANS_YR4_RT","FEMALE_UNKN_ORIG_YR4_RT","FEMALE_UNKN_4YR_TRANS_YR4_RT","FEMALE_UNKN_2YR_TRANS_YR4_RT","MALE_DEATH_YR4_RT","MALE_COMP_ORIG_YR4_RT","MALE_COMP_4YR_TRANS_YR4_RT","MALE_COMP_2YR_TRANS_YR4_RT","MALE_WDRAW_ORIG_YR4_RT","MALE_WDRAW_4YR_TRANS_YR4_RT","MALE_WDRAW_2YR_TRANS_YR4_RT","MALE_ENRL_ORIG_YR4_RT","MALE_ENRL_4YR_TRANS_YR4_RT","MALE_ENRL_2YR_TRANS_YR4_RT","MALE_UNKN_ORIG_YR4_RT","MALE_UNKN_4YR_TRANS_YR4_RT","MALE_UNKN_2YR_TRANS_YR4_RT","PELL_DEATH_YR4_RT","PELL_COMP_ORIG_YR4_RT","PELL_COMP_4YR_TRANS_YR4_RT","PELL_COMP_2YR_TRANS_YR4_RT","PELL_WDRAW_ORIG_YR4_RT","PELL_WDRAW_4YR_TRANS_YR4_RT","PELL_WDRAW_2YR_TRANS_YR4_RT","PELL_ENRL_ORIG_YR4_RT","PELL_ENRL_4YR_TRANS_YR4_RT","PELL_ENRL_2YR_TRANS_YR4_RT","PELL_UNKN_ORIG_YR4_RT","PELL_UNKN_4YR_TRANS_YR4_RT","PELL_UNKN_2YR_TRANS_YR4_RT","NOPELL_DEATH_YR4_RT","NOPELL_COMP_ORIG_YR4_RT","NOPELL_COMP_4YR_TRANS_YR4_RT","NOPELL_COMP_2YR_TRANS_YR4_RT","NOPELL_WDRAW_ORIG_YR4_RT","NOPELL_WDRAW_4YR_TRANS_YR4_RT","NOPELL_WDRAW_2YR_TRANS_YR4_RT","NOPELL_ENRL_ORIG_YR4_RT","NOPELL_ENRL_4YR_TRANS_YR4_RT","NOPELL_ENRL_2YR_TRANS_YR4_RT","NOPELL_UNKN_ORIG_YR4_RT","NOPELL_UNKN_4YR_TRANS_YR4_RT","NOPELL_UNKN_2YR_TRANS_YR4_RT","LOAN_DEATH_YR4_RT","LOAN_COMP_ORIG_YR4_RT","LOAN_COMP_4YR_TRANS_YR4_RT","LOAN_COMP_2YR_TRANS_YR4_RT","LOAN_WDRAW_ORIG_YR4_RT","LOAN_WDRAW_4YR_TRANS_YR4_RT","LOAN_WDRAW_2YR_TRANS_YR4_RT","LOAN_ENRL_ORIG_YR4_RT","LOAN_ENRL_4YR_TRANS_YR4_RT","LOAN_ENRL_2YR_TRANS_YR4_RT","LOAN_UNKN_ORIG_YR4_RT","LOAN_UNKN_4YR_TRANS_YR4_RT","LOAN_UNKN_2YR_TRANS_YR4_RT","NOLOAN_DEATH_YR4_RT","NOLOAN_COMP_ORIG_YR4_RT","NOLOAN_COMP_4YR_TRANS_YR4_RT","NOLOAN_COMP_2YR_TRANS_YR4_RT","NOLOAN_WDRAW_ORIG_YR4_RT","NOLOAN_WDRAW_4YR_TRANS_YR4_RT","NOLOAN_WDRAW_2YR_TRANS_YR4_RT","NOLOAN_ENRL_ORIG_YR4_RT","NOLOAN_ENRL_4YR_TRANS_YR4_RT","NOLOAN_ENRL_2YR_TRANS_YR4_RT","NOLOAN_UNKN_ORIG_YR4_RT","NOLOAN_UNKN_4YR_TRANS_YR4_RT","NOLOAN_UNKN_2YR_TRANS_YR4_RT","FIRSTGEN_DEATH_YR4_RT","FIRSTGEN_COMP_ORIG_YR4_RT","FIRSTGEN_COMP_4YR_TRANS_YR4_RT","FIRSTGEN_COMP_2YR_TRANS_YR4_RT","FIRSTGEN_WDRAW_ORIG_YR4_RT","FIRSTGEN_WDRAW_4YR_TRANS_YR4_RT","FIRSTGEN_WDRAW_2YR_TRANS_YR4_RT","FIRSTGEN_ENRL_ORIG_YR4_RT","FIRSTGEN_ENRL_4YR_TRANS_YR4_RT","FIRSTGEN_ENRL_2YR_TRANS_YR4_RT","FIRSTGEN_UNKN_ORIG_YR4_RT","FIRSTGEN_UNKN_4YR_TRANS_YR4_RT","FIRSTGEN_UNKN_2YR_TRANS_YR4_RT","NOT1STGEN_DEATH_YR4_RT","NOT1STGEN_COMP_ORIG_YR4_RT","NOT1STGEN_COMP_4YR_TRANS_YR4_RT","NOT1STGEN_COMP_2YR_TRANS_YR4_RT","NOT1STGEN_WDRAW_ORIG_YR4_RT","NOT1STGEN_WDRAW_4YR_TRANS_YR4_RT","NOT1STGEN_WDRAW_2YR_TRANS_YR4_RT","NOT1STGEN_ENRL_ORIG_YR4_RT","NOT1STGEN_ENRL_4YR_TRANS_YR4_RT","NOT1STGEN_ENRL_2YR_TRANS_YR4_RT","NOT1STGEN_UNKN_ORIG_YR4_RT","NOT1STGEN_UNKN_4YR_TRANS_YR4_RT","NOT1STGEN_UNKN_2YR_TRANS_YR4_RT","RPY_1YR_RT","COMPL_RPY_1YR_RT","NONCOM_RPY_1YR_RT","LO_INC_RPY_1YR_RT","MD_INC_RPY_1YR_RT","HI_INC_RPY_1YR_RT","DEP_RPY_1YR_RT","IND_RPY_1YR_RT","PELL_RPY_1YR_RT","NOPELL_RPY_1YR_RT","FEMALE_RPY_1YR_RT","MALE_RPY_1YR_RT","FIRSTGEN_RPY_1YR_RT","NOTFIRSTGEN_RPY_1YR_RT","INC_PCT_LO","DEP_STAT_PCT_IND","DEP_INC_PCT_LO","IND_INC_PCT_LO","PAR_ED_PCT_1STGEN","INC_PCT_M1","INC_PCT_M2","INC_PCT_H1","INC_PCT_H2","DEP_INC_PCT_M1","DEP_INC_PCT_M2","DEP_INC_PCT_H1","DEP_INC_PCT_H2","IND_INC_PCT_M1","IND_INC_PCT_M2","IND_INC_PCT_H1","IND_INC_PCT_H2","PAR_ED_PCT_MS","PAR_ED_PCT_HS","PAR_ED_PCT_PS","APPL_SCH_PCT_GE2","APPL_SCH_PCT_GE3","APPL_SCH_PCT_GE4","APPL_SCH_PCT_GE5","DEP_INC_AVG","IND_INC_AVG","OVERALL_YR2_N","LO_INC_YR2_N","MD_INC_YR2_N","HI_INC_YR2_N","DEP_YR2_N","IND_YR2_N","FEMALE_YR2_N","MALE_YR2_N","PELL_YR2_N","NOPELL_YR2_N","LOAN_YR2_N","NOLOAN_YR2_N","FIRSTGEN_YR2_N","NOT1STGEN_YR2_N","OVERALL_YR3_N","DEBT_MDN","GRAD_DEBT_MDN","WDRAW_DEBT_MDN","LO_INC_DEBT_MDN","MD_INC_DEBT_MDN","HI_INC_DEBT_MDN","DEP_DEBT_MDN","IND_DEBT_MDN","PELL_DEBT_MDN","NOPELL_DEBT_MDN","FEMALE_DEBT_MDN","MALE_DEBT_MDN","FIRSTGEN_DEBT_MDN","NOTFIRSTGEN_DEBT_MDN","DEBT_N","GRAD_DEBT_N","WDRAW_DEBT_N","LO_INC_DEBT_N","MD_INC_DEBT_N","HI_INC_DEBT_N","DEP_DEBT_N","IND_DEBT_N","PELL_DEBT_N","NOPELL_DEBT_N","FEMALE_DEBT_N","MALE_DEBT_N","FIRSTGEN_DEBT_N","NOTFIRSTGEN_DEBT_N","GRAD_DEBT_MDN10YR","CUML_DEBT_N","CUML_DEBT_P90","CUML_DEBT_P75","CUML_DEBT_P25","CUML_DEBT_P10","INC_N","DEP_INC_N","IND_INC_N","DEP_STAT_N","PAR_ED_N","APPL_SCH_N","RPY_1YR_N","COMPL_RPY_1YR_N","NONCOM_RPY_1YR_N","LO_INC_RPY_1YR_N","MD_INC_RPY_1YR_N","HI_INC_RPY_1YR_N","DEP_RPY_1YR_N","IND_RPY_1YR_N","PELL_RPY_1YR_N","NOPELL_RPY_1YR_N","FEMALE_RPY_1YR_N","MALE_RPY_1YR_N","FIRSTGEN_RPY_1YR_N","NOTFIRSTGEN_RPY_1YR_N","HCM2","count_ed","loan_ever","pell_ever","age_entry","age_entry_sq","agege24","female","married","dependent","veteran","first_gen","faminc","md_faminc","faminc_ind","lnfaminc","lnfaminc_ind","median_hh_inc","poverty_rate","unemp_rate","ln_median_hh_inc","fsend_count","fsend_1","fsend_2","fsend_3","fsend_4","fsend_5","count_nwne_p10","count_wne_p10","mn_earn_wne_p10","md_earn_wne_p10","pct10_earn_wne_p10","pct25_earn_wne_p10","pct75_earn_wne_p10","pct90_earn_wne_p10","sd_earn_wne_p10","count_wne_inc1_p10","count_wne_inc2_p10","count_wne_inc3_p10","count_wne_indep0_inc1_p10","count_wne_indep0_p10","count_wne_indep1_p10","count_wne_male0_p10","count_wne_male1_p10","gt_25k_p10","mn_earn_wne_inc1_p10","mn_earn_wne_inc2_p10","mn_earn_wne_inc3_p10","mn_earn_wne_indep0_inc1_p10","mn_earn_wne_indep0_p10","mn_earn_wne_indep1_p10","mn_earn_wne_male0_p10","mn_earn_wne_male1_p10","DEBT_MDN_SUPP","GRAD_DEBT_MDN_SUPP","GRAD_DEBT_MDN10YR_SUPP","RPY_3YR_RT_SUPP","LO_INC_RPY_3YR_RT_SUPP","MD_INC_RPY_3YR_RT_SUPP","HI_INC_RPY_3YR_RT_SUPP","COMPL_RPY_3YR_RT_SUPP","NONCOM_RPY_3YR_RT_SUPP","DEP_RPY_3YR_RT_SUPP","IND_RPY_3YR_RT_SUPP","PELL_RPY_3YR_RT_SUPP","NOPELL_RPY_3YR_RT_SUPP","FEMALE_RPY_3YR_RT_SUPP","MALE_RPY_3YR_RT_SUPP","FIRSTGEN_RPY_3YR_RT_SUPP","NOTFIRSTGEN_RPY_3YR_RT_SUPP","C150_L4_POOLED_SUPP","C150_4_POOLED_SUPP","C200_L4_POOLED_SUPP","C200_4_POOLED_SUPP"]
filenames.reverse()
header = uselessid + allid
def removeNull():
	for ar in filenames :
		print 'start read'
		df = pd.read_csv('data/'+ar, header=0)
		df.columns = header
		lens = len(df)
		df[uselessid] = df[uselessid].astype(object)
		print 'end read'
		for l in allid:
			#std = (df[l].max() - df[l].min())
			#mean = df[l].mean()
			df.loc[df[l].isnull(),l] = 0
			df[l] = preprocessing.scale(np.array(df[l]))
			#df.loc[df[l].isnull(),l] = mean
			#df.loc[l] = (df[l] - mean) / std
		df = df.ix[:lens]
		df.to_csv('result/'+ar, index = False)#, columns = allid)
		print ar

def showData(school_id = False):
	dfs = []
	test = 0 
	for ar in filenames:
		df = pd.read_csv('result/'+ar, header=0, low_memory=False)	
		#del df['Unnamed: 472']
		df.columns = header
		dfs.append(df)
		print ar
		if test>=1:
			break
		test+=1
	
	x=['1996-11-04 22:23:00', '1997-11-04 22:23:00', '1998-11-04 22:23:00', '1999-11-04 22:23:00', '2000-11-04 22:23:00', '2001-11-04 22:23:00', '2002-11-04 22:23:00', '2003-11-04 22:23:00', '2004-11-04 22:23:00', '2005-11-04 22:23:00', '2006-11-04 22:23:00', '2007-11-04 22:23:00', '2008-11-04 22:23:00', '2009-11-04 22:23:00', '2010-11-04 22:23:00', '2011-11-04 22:23:00', '2012-11-04 22:23:00', '2013-11-04 22:23:00']
	
	if school_id:
		data = []
		for value in allid:
			info = [0]*len(dfs)
			print '\n\n'+value
			for i in xrange(0,len(dfs)):
				df = dfs[i]
				print str(i) + '\t',
				print df.loc(df['UNITID']==school_id,value)
				info[i] = df.loc(df['UNITID']==school_id,value)
				print info[i]
			print info
			data.append([
				go.Scatter(
					x=x,
					y=info[:],
					name=value
				)
			])
		layout = go.Layout(xaxis=dict(title='Years'),yaxis=dict(title='Param'))
		fig = go.Figure(data=data, layout=layout)
		plot_url = py.plot(fig, filename='latex')
if __name__ == '__main__':
	removeNull()
	#showData(107974)
